### PR TITLE
update header files for react-native 0.40.0

### PR DESCRIPTION
**Pull request by jaylingelbach**

### CODE REVIEW

**Comment by frankrowe** [comment]
Looks good! Can you also bump the version in the `package.json` to 0.9.5?

**Comment by frankrowe** [comment]
Also we'll need to update the react-native dependency to 0.40.0. And maybe the React dependency if 0.40 requires a newer version of React

https://github.com/boundlessgeo/react-native-spatialconnect/blob/master/package.json#L22

**Comment by jaylingelbach** [comment]
Looks like react has the latest version.

**Comment by frankrowe** [comment]
:+1:

**Pull request merged**
